version: '3.8'

services:

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: 'win10'
      RAM_SIZE: '1.5G'
      CPU_CORES: '1'
      DISK_SIZE: '64G'
    volumes:
      - windows_data:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

volumes:
  windows_data: