version: '3.8'

services:
  infoportal:
    image: ofterdinger/regatta-infoportal:latest
    container_name: infoportal
    hostname: ${HOST_NAME}
    restart: always
    ports:
      - 443:8443
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HTTPS_CERT_PATH=/data/ssl/cert.pem
      - HTTPS_KEY_PATH=/data/ssl/privkey.pem
      - RUST_LOG=${RUST_LOG}
    volumes:
      - '${HOST_CERT_FILE}:/data/ssl/cert.pem:ro'
      - '${HOST_PRIVKEY_FILE}:/data/ssl/privkey.pem:ro'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
