version: '3.7'

services:
  infoportal:
    image: ofterdinger/regatta-infoportal:latest
    container_name: infoportal
    hostname: ${HOST_NAME}
    restart: always
    ports:
      - 443:8443
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HTTPS_CERT_PATH=/data/ssl/cert.pem
      - HTTPS_KEY_PATH=/data/ssl/privkey.pem
      - ACTIVE_REGATTA_ID=${ACTIVE_REGATTA_ID}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - '${HOST_CERT_FILE}:/data/ssl/cert.pem:ro'
      - '${HOST_PRIVKEY_FILE}:/data/ssl/privkey.pem:ro'
