global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:

  - job_name: infoportal
    static_configs:
      - targets: ['infoportal:8080']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']