version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    command: --cleanup --include-restarting --include-stopped --tlsverify --schedule "0 0 3 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
