version: "3.7"

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    container_name: ${NAME}
    hostname: ${HOST_NAME}
    restart: always
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_LCID=1031
      - MSSQL_COLLATION=Latin1_General_CI_AS
      - MSSQL_DUMP_DIR=/mssql/dump
      - MSSQL_MASTER_LOG_FILE=/mssql/log/mastlog.ldf
      - MSSQL_MASTER_DATA_FILE=/mssql/data/master.mdf
      - MSSQL_BACKUP_DIR=/mssql/backup
      - MSSQL_LOG_DIR=/mssql/log
      - MSSQL_DATA_DIR=/mssql/data
      - MSSQL_AGENT_ENABLED=true
    volumes:
      - '${HOST_DATA_DIR}:/mssql:rw'
      - '${HOST_FULLCHAIN_FILE}:/mssql/ssl/fullchain.pem:ro'
      - '${HOST_CERT_FILE}:/mssql/ssl/cert.pem:ro'
      - '${HOST_PRIVKEY_FILE}:/mssql/ssl/privkey.pem:ro'
      - './mssql.conf:/var/opt/mssql/mssql.conf:ro'
